### ISSUE TITLE
Como faço para rodar o projeto?

### ISSUE THREAD

**Issue by Davi-Noah** [hermeson883/INfinityLit#2]
Como faço para rodar o projeto na minha máquina?

**Comment by hermeson883** [comment]
> _No description provided._

Opa @Davi-Noah, para você rodar o projeto basta apenas rodar o seguinte comando no terminal: 
```
pip install requirements.txt
```

Feito isso você pode rodar agora o projeto com o seguinte comando: 

```
streamlit run project.py
```

**Comment by hermeson883** [comment]
> > _No description provided._
> 
> Opa @Davi-Noah, para você rodar o projeto basta apenas rodar o seguinte comando no terminal:
> 
> ```
> pip install requirements.txt
> ```
> 
> Feito isso você pode rodar agora o projeto com o seguinte comando:
> 
> ```
> streamlit run project.py
> ```
